datasources.default.driverClassName = 'org.h2.Driver'
netty.default.allocator.max-order = 3

[micronaut]
application.name = 'fileProcessorService'
metrics.enabled = true

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'
